steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/caddyingress:${TAG_NAME}", "-f", "./Dockerfile", "."]
images: ["gcr.io/${PROJECT_ID}/caddyingress:${TAG_NAME}"]